name: Go Build

on: 
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Set up Go.
        uses: actions/setup-go@v4
        with:
          go-version: ^1.21
      - name: Build
        run: |
          export CGO_ENABLED=0
          export GOOS=linux
          go build -ldflags="-w -s" -o eks-auth .
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: eks-auth
          path: ./eks-auth