name: Build and Release

on:
  push:
    tags:
      - "v*.*.*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Set up Go.
        uses: actions/setup-go@v4
        with:
          go-version: ^1.21
      - name: Build
        run: |
          export CGO_ENABLED=0
          export GOOS=linux
          go build -ldflags="-w -s" -o eks-auth .
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: eks-auth
          generate_release_notes: true
